server:
  port: 8004

dubbo:
  # 配置服务信息
  application:
    id: module-provider
    name: module-provider
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    id: module-registry
    address: nacos://127.0.0.1:8848
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  scan:
    base-packages: com.kevin.demo.dubbo.service.impl
  provider:
    version: 1.0.0

nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: public

spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
  datasource:
    order:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/order_bj?setUnicode=true&characterEncoding=utf8
      username: root
      password: root
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      maxLifetime: 20000
      maxPoolSize: 25
      minPoolSize: 3
      uniqueResourceName: orderDataSource
      testQuery: select 1
    storage:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/storage_bj?setUnicode=true&characterEncoding=utf8
      username: root
      password: root
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      maxLifetime: 20000
      maxPoolSize: 25
      minPoolSize: 3
      uniqueResourceName: storageDataSource
      testQuery: select 1

logging:
  config : classpath:config/log/log4j2.xml